- name: Terraform Deploy
  ansible.builtin.shell:
    cmd: terraform apply -auto-approve
    chdir: /root/vscode/salt-infra-master/terraform/proxmox
  environment:
    PM_PASS: "{{ terraform_password }}"
  tags:
    - terraform_apply
  ignore_errors: True

# only run this one if its specifically tagged with terraform_destroy! (never)
- name: Terraform Destroy
  ansible.builtin.shell:
    cmd: terraform destroy -auto-approve
    chdir: /root/vscode/salt-infra-master/terraform/proxmox
  environment:
    PM_PASS: "{{ terraform_password }}"
  tags:
    - terraform_destroy
    - never
  ignore_errors: True