#cloud-config
output: {all: '| tee -a /var/log/cloud-init-output.log'}
users:
  - default
  - name: jon
    gecos: jon
    primary_group: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, sudo
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJjM78UyIQWNbMsca2qafeshPflijH8HbbsKuTTZqB1F jon@DESKTOP-SNM4E2
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGlAs2ApLH1sTfDTfYvFDcDS5cyAdkCqcJ28D+4Lpuyo jon@troon
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJpASWQUj+UkSv2M4kgxMEeM3oUYtKI54N1CVnwKrk9A root@salt 
# Run 'apt-get update' on first boot
apt_update: true
# Run 'apt-get upgrade' on first boot
apt_upgrade: true

write_files:
  - path: /tmp/salt-bootstrap-script.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      
      sudo wget -O bootstrap-salt.sh https://bootstrap.saltstack.com;
      sudo chmod 700 bootstrap-salt.sh;
      sudo ./bootstrap-salt.sh -A 86.29.22.70;
runcmd:
  - /tmp/salt-bootstrap-script.sh
# important to allow salt to managed hosts file
manage_etc_hosts: false
# dont change hostname
preserve_hostname: true

network:
  version: 2
  ethernets:
    switchports:
      match:
        name: eth*
      mtu: 1390